### ISSUE TITLE
Remove constraint on cvxopt

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/kvxopt-feedstock#26]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I don't understand why this package has a constraint of cvxopt =999999999.  This package installs to a kvxopt directory vs a cvxopt directory for that package, so I don't see why this should be incompatible with also having cvxopt installed.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by sanurielf** [comment]
Hi @DManowitz ,

There is one header file (cvxopt.h) which is installed globally. Will check if we can rename it.
